apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
