-- =============================================================================
-- Machine Troubleshooter — Seed Data
-- =============================================================================
-- Demo data for testing the UI and RAG pipeline.
-- These are FICTIONAL machines and manuals, not real products.
--
-- Key test scenario: Error code E101 exists in BOTH machines with
-- DIFFERENT meanings, demonstrating cross-manual ambiguity handling.
-- =============================================================================

-- ========================
-- Machines
-- ========================

INSERT INTO machines (id, name, model_number, manufacturer, category, description)
VALUES
    (
        '11111111-1111-1111-1111-111111111111',
        'CNC Milling Machine X100',
        'CNC-X100',
        'FictionalMachinery Inc.',
        'CNC',
        'High-precision 5-axis CNC milling machine for industrial manufacturing'
    ),
    (
        '22222222-2222-2222-2222-222222222222',
        'Hydraulic Press Z200',
        'PRESS-Z200',
        'FictionalMachinery Inc.',
        'Press',
        '200-ton hydraulic press for metal forming and stamping operations'
    )
ON CONFLICT (model_number) DO NOTHING;


-- ========================
-- Manuals
-- ========================

INSERT INTO manuals (id, machine_id, title, filename, total_pages, status)
VALUES
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        '11111111-1111-1111-1111-111111111111',
        'CNC-X100 Service Manual',
        'CNC-X100_Service_Manual.pdf',
        350,
        'ready'
    ),
    (
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        '22222222-2222-2222-2222-222222222222',
        'PRESS-Z200 Service Manual',
        'PRESS-Z200_Service_Manual.pdf',
        280,
        'ready'
    )
ON CONFLICT DO NOTHING;


-- ========================
-- Document Chunks (without embeddings — those are generated by the pipeline)
-- ========================

-- CNC-X100: E101 = Motor Overheating
INSERT INTO document_chunks (id, manual_id, machine_id, page_number, section, chunk_index, content, content_type, error_codes, metadata)
VALUES
    (
        'c1000001-0000-0000-0000-000000000001',
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        '11111111-1111-1111-1111-111111111111',
        214,
        'Troubleshooting',
        0,
        'Error E101 — Spindle Motor Overheating

This error indicates that the spindle motor temperature has exceeded the safe operating threshold of 85°C.

Probable Causes:
1. Insufficient coolant flow to spindle motor cooling jacket
2. Blocked air intake vents on the spindle motor housing
3. Excessive continuous operation beyond rated duty cycle
4. Worn spindle bearings causing increased friction
5. Ambient temperature exceeding 40°C in machine enclosure

Corrective Steps:
1. Immediately reduce spindle speed to 50% or stop the spindle
2. Check coolant level and flow rate (minimum 2.5 L/min required)
3. Inspect and clean air intake vents and cooling fans
4. Verify bearing condition using vibration analysis
5. Allow motor to cool below 60°C before resuming operation

WARNING: Do not open the spindle motor housing while the machine is powered on. Disconnect main power and wait 5 minutes before inspection.',
        'text',
        ARRAY['E101'],
        '{"severity": "high", "requires_shutdown": true}'
    ),
    (
        'c1000002-0000-0000-0000-000000000002',
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        '11111111-1111-1111-1111-111111111111',
        215,
        'Troubleshooting',
        1,
        'Error E102 — Axis Position Error

The CNC controller has detected a discrepancy between the commanded position and the actual position of one or more axes exceeding the allowable tolerance of 0.01mm.

Probable Causes:
1. Encoder feedback cable loose or damaged
2. Servo motor malfunction
3. Ballscrew backlash exceeding specification
4. Mechanical obstruction in axis travel path
5. Controller parameter drift

Corrective Steps:
1. Check encoder cables and connections on the affected axis
2. Run axis calibration routine from the maintenance menu
3. Measure and adjust ballscrew backlash compensation
4. Inspect axis guides and ways for debris or damage
5. If error persists, contact service for servo motor diagnosis',
        'text',
        ARRAY['E102'],
        '{"severity": "medium", "requires_shutdown": false}'
    ),
    (
        'c1000003-0000-0000-0000-000000000003',
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        '11111111-1111-1111-1111-111111111111',
        50,
        'Maintenance',
        0,
        'CNC-X100 Regular Maintenance Schedule

Daily Maintenance:
- Check coolant level and top up if below minimum mark
- Clean chip trays and filters
- Verify all axis movements are smooth
- Check spindle runout with dial indicator

Weekly Maintenance:
- Lubricate all linear guides and ballscrews
- Clean and inspect tool changer mechanism
- Check hydraulic pressure (should read 70-80 bar)
- Inspect electrical connections for looseness

Monthly Maintenance:
- Replace coolant filters
- Calibrate all axes using laser interferometer
- Inspect spindle bearings for wear
- Update machine logs with maintenance records',
        'text',
        ARRAY[]::text[],
        '{"severity": "info", "requires_shutdown": false}'
    );


-- PRESS-Z200: E101 = Hydraulic Pressure Low (DIFFERENT meaning than CNC-X100 E101)
INSERT INTO document_chunks (id, manual_id, machine_id, page_number, section, chunk_index, content, content_type, error_codes, metadata)
VALUES
    (
        'c2000001-0000-0000-0000-000000000001',
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        '22222222-2222-2222-2222-222222222222',
        178,
        'Troubleshooting',
        0,
        'Error E101 — Hydraulic System Pressure Low

This error is triggered when the main hydraulic system pressure drops below the minimum operating threshold of 150 bar during a press cycle.

Probable Causes:
1. Hydraulic fluid level below minimum in the reservoir
2. Hydraulic pump worn or failing (check flow rate)
3. Pressure relief valve stuck open or misadjusted
4. External or internal hydraulic line leak
5. Clogged hydraulic filter restricting flow
6. Air contamination in the hydraulic system

Corrective Steps:
1. Check hydraulic fluid level in reservoir — add ISO VG 46 fluid if low
2. Inspect all hydraulic lines and fittings for visible leaks
3. Check and replace hydraulic filter if pressure differential exceeds 3 bar
4. Verify pressure relief valve setting (should be 210 bar)
5. Bleed air from the hydraulic system using the bleed valves
6. If pump is suspected, measure pump flow rate (minimum 40 L/min at 200 bar)

SAFETY: Never work under a raised press ram without safety blocks in place. Lock out / tag out before inspecting hydraulic components.',
        'text',
        ARRAY['E101'],
        '{"severity": "high", "requires_shutdown": true}'
    ),
    (
        'c2000002-0000-0000-0000-000000000002',
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        '22222222-2222-2222-2222-222222222222',
        179,
        'Troubleshooting',
        1,
        'Error E201 — Ram Position Sensor Fault

The linear position sensor on the press ram is reporting invalid readings or has lost communication with the controller.

Probable Causes:
1. Position sensor cable damaged or disconnected
2. Sensor head contaminated with hydraulic fluid or debris
3. Sensor electronics failure
4. Electromagnetic interference from nearby equipment
5. Controller input card malfunction

Corrective Steps:
1. Inspect sensor cable routing and connections
2. Clean sensor head and measurement strip with approved solvent
3. Check sensor output voltage (should be 0.5V to 4.5V proportional to position)
4. Verify electromagnetic shielding on sensor cables
5. If cleaning and reconnection do not resolve, replace sensor assembly (Part #PZ200-SENS-01)',
        'text',
        ARRAY['E201'],
        '{"severity": "high", "requires_shutdown": true}'
    );
