global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'machine-troubleshooter-backend'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000', 'host.docker.internal:8000']
        labels:
          app: 'machine-troubleshooter'
          environment: 'local'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
